Qualanex.QoskCloud.Web/Areas/QoskReporting/Controllers/AzureImageController.cs
using Qualanex.QoskCloud.Web.Areas.QoskReporting.Models;
using Qualanex.QoskCloud.Web.Areas.QoskReporting.Utility;
using Qualanex.QoskCloud.Web.Areas.QoskReporting.Utility.Common;
using Qualanex.QoskCloud.Web.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace Qualanex.QoskCloud.Web.Areas.QoskReporting.Controllers
{
    public class AzureImageController : AsyncController
    {
        public const string AzureThumbInfoCache = "AzureThumbInfoCache";

        // POST: QoskReporting/AzureImage/Json
        // GET: QoskReporting/AzureImage/Json
        [AllowAnonymous]
        public ActionResult Json(string prefixHex, bool runDaily)
        {
            AzureThumbInfo thumbInfo = new AzureThumbInfo()
            {
                PrefixHex = prefixHex,
                RunDaily = runDaily
            };
            GenerateThumbs(thumbInfo);

            return Json(thumbInfo, JsonRequestBehavior.AllowGet);
        }

        // POST: QoskReporting/AzureImage
        // GET: QoskReporting/AzureImage
        [AllowAnonymous]
        public ActionResult Index(AzureThumbInfo thumbInfo)
        {            
            if(!GenerateThumbs(thumbInfo))
                SetDefaults(thumbInfo);

            return View(thumbInfo);
        }

        private static bool GenerateThumbs(AzureThumbInfo thumbInfo)
        {
            // see if we are still running a previous job
            var previousRun = MemCacheManager.Get<AzureThumbInfo>(AzureThumbInfoCache);
            if (previousRun != null && (previousRun.IsComplete || previousRun.Stop))
                MemCacheManager.Remove(AzureThumbInfoCache);


            if (!MemCacheManager.IsSet(AzureThumbInfoCache) && (thumbInfo.RunWithNoPrefix || !string.IsNullOrWhiteSpace(thumbInfo.PrefixHex)))
            {
                SetDefaults(thumbInfo);

                MemCacheManager.Set(AzureThumbInfoCache, thumbInfo, 300);

                // using QueueBackgroundWorkItem will help prevent IIS from ending the background task
                HostingEnvironment.QueueBackgroundWorkItem(ct => ReportingBlobResource.GenerateAzureImageThumbsAsync(ct, thumbInfo));
                return true;
            }

            return false;
        }

        private static void SetDefaults(AzureThumbInfo thumbInfo)
        {
            if (thumbInfo.RunWithNoPrefix)
                thumbInfo.PrefixHex = string.Empty;

            if (thumbInfo.MaxContainers <= 0)
                thumbInfo.MaxContainers = 10000;
            if (thumbInfo.MaxParallelThreads <= 0)
                thumbInfo.MaxParallelThreads = 10;
            if (thumbInfo.ContainersPerFetch <= 0)
                thumbInfo.ContainersPerFetch = 500;
        }

        [AllowAnonymous]
        public ActionResult Progress()
        {
            var info = MemCacheManager.Get<AzureThumbInfo>(AzureThumbInfoCache);

            var result = info == null ? new AzureThumbResult() : new AzureThumbResult()
            {
                ImagesCreated = info.ImagesCreated,
                ContainersProcessed = info.ContainersProcessed,
                ContainerSetsFetched = info.ContainerSetsFetched,
                ContainersAlreadyExisted = info.ContainersAlreadyExisted,
                StartTime = info.StartTime.ToString(),
                EndTime = info.EndTime.HasValue ? info.EndTime.ToString() : null,
                RunTime = info.RunTime,
                Status = info.Status,
                IsComplete = info.IsComplete,
                PrefixHex = info.PrefixHex,
                NextPrefixHex = info.NextPrefixHex
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public ActionResult Stop()
        {
            var info = MemCacheManager.Get<AzureThumbInfo>(AzureThumbInfoCache);
            info.Stop = true;

            return Json(null, JsonRequestBehavior.AllowGet);
        }
    }
}

Qualanex.QoskCloud.Web/Areas/QoskReporting/Views/AzureImage/Index.cshtml
@model Qualanex.QoskCloud.Web.Areas.QoskReporting.Models.AzureThumbInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Areas/QoskReporting/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Areas/QoskReporting/Scripts/jquery-3.3.1.min.js")"></script>
    <script src="@Url.Content("~/Areas/QoskReporting/Scripts/bootstrap.min.js")"></script>
    <title>View</title>
    <style>
        .col-md-2 {
            text-align: right;
        }
        hr {
            margin: 0 0 5px 0;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal container">
        <h4>AzureThumbInfo</h4>

        <hr />
        <hr />

        <div>Polling for Progress in ... <strong id="pollTime">3</strong> seconds</div>

        <hr />
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.PrefixHex, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="PrefixHexDiv">
                @Model.PrefixHex
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="StatusDiv">
                @Model.Status
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagesCreated, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="ImagesCreatedDiv">
                @Model.ImagesCreated
            </div>
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.ContainersProcessed, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="ContainersProcessedDiv">
                @Model.ContainersProcessed
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContainerSetsFetched, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="ContainerSetsFetchedDiv">
                @Model.ContainerSetsFetched
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContainersAlreadyExisted, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="ContainersAlreadyExistedDiv">
                @Model.ContainersAlreadyExisted
            </div>
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="StartTimeDiv">
                @Model.StartTime
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RunTime, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="RunTimeDiv">
                @Model.RunTime
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="EndTimeDiv">
                @Model.EndTime
            </div>
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.IsComplete, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10" id="IsCompleteDiv">
                @Model.IsComplete
            </div>
        </div>

        <hr />

        <div class="form-group">
            <label class="col-md-2">
                JsonFullResults
            </label>
            <div class="col-md-10" style="word-wrap:break-word" id="JsonFullResultsDiv">
            </div>
        </div>

        <hr />
        <hr />

        <h4>Generate Thumbs For:</h4>

        <div class="form-group">
            @Html.LabelFor(model => model.PrefixHex, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrefixHex, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RunWithNoPrefix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RunWithNoPrefix, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxParallelThreads, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxParallelThreads, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContainersPerFetch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContainersPerFetch, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxContainers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxContainers, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RunForExistingContainers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RunForExistingContainers, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RunDaily, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RunDaily, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="RunBtn" type="submit" value="Run!" class="btn btn-default" />
                &nbsp;
                <input id="StopBtn" type="button" value="Stop Running" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

<script>

    var pollSeconds = 4;
    function pollCountdown() {
        pollSeconds--;
        $("#pollTime").text(pollSeconds);

        if (pollSeconds <= 0) {
            pollForProgress();
            pollSeconds = 4;
        } else {
            setTimeout(pollCountdown, 1000);
        }
    }

    function pollForProgress() {
        $.get('@Url.Action("Progress", "AzureImage")', function (data) {
            $("#PrefixHexDiv").html(data.PrefixHex);
            $("#StatusDiv").html(data.Status);
            $("#ImagesCreatedDiv").html(data.ImagesCreated);
            $("#ContainersProcessedDiv").html(data.ContainersProcessed);
            $("#ContainerSetsFetchedDiv").html(data.ContainerSetsFetched);
            $("#ContainersAlreadyExistedDiv").html(data.ContainersAlreadyExisted);            
            $("#TotalContainerCountDiv").html(data.TotalContainerCount);
            $("#StartTimeDiv").html(data.StartTime);
            $("#EndTimeDiv").html(data.EndTime);
            $("#RunTimeDiv").html(data.RunTime);
            $("#IsCompleteDiv").html(data.IsComplete);

            // set the old prefixHex to the next one, so we can run the next set
            $("#PrefixHex").val(data.NextPrefixHex);
            $("#JsonFullResultsDiv").html(JSON.stringify(data));

            if (!data.IsComplete && data.StartTime) {
                setTimeout(pollCountdown, 1000);
                $("#RunBtn").attr("disabled", true);
                $("#PrefixHex").attr("disabled", true);

            } else {
                $("#RunBtn").attr("disabled", false);
                $("#PrefixHex").attr("disabled", false);
            }
        });
    }

    $(document).ready(function () {        
        setTimeout(pollCountdown, 1000);

        $("#StopBtn").click(function () {
            $.get('@Url.Action("Stop", "AzureImage")');
        });
    });
</script>
</body>
</html>